version: '3.4'

networks:
  authorization-dev:
    driver: bridge
  services_dev:
    external: true
    name: services_dev

services:
  authorization-api:
    image: ${DOCKER_REGISTRY-}authorization-api
    container_name: 'authorization-api'
    build: 
      context: .
      dockerfile: authorization-api.dockerfile
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      ASPNETCORE_HTTPS_PORT: 8083
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
    networks:
      - services_dev
      - authorization-dev
    env_file:
      - .env-dev  

  authorization-ui:
    image: ${DOCKER_REGISTRY-}authorization-ui
    container_name: 'authorization-ui'
    build: 
      context: .
      dockerfile: authorization-ui.dockerfile
    ports:
      - "8084:80"
      - "8085:443"
    environment:
      ASPNETCORE_HTTPS_PORT: 8085
      #- VIRTUAL_HOST=sub.domain-example.com
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
    networks:
      - authorization-dev
    env_file:
      - .env-dev
    depends_on:
      - authorization-api